image:
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  global:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD:
      secure: H7PI8imJTED02mGoIPpDn08+ku988jV+XX2oa4LAMHEHpa8DSnqMitpxieedr4YsP/xtLGqpk0rTFpVawtp3co6317tL8U0kNasd/ZppV7jDOiZN6qOaE97zKf7xOA37WsDd/5qhx1SRRRtLr5hepDu2dSKcQjH6w/rRtLP1SNNijnxEJNf1LZEirg5f55HvEplGwcTnM0V/F2FhgCpRuNFN9e3zcHXVTE9fS2m5BcU=

  matrix:
    - PYTHON: "C:\\Python36\\python"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "32"
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      appveyor_build_worker_image: Visual Studio 2017

    - PYTHON: "C:\\Python37\\python"
      PYTHON_VERSION: "3.7.4"
      PYTHON_ARCH: "32"
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      appveyor_build_worker_image: Visual Studio 2017

    - PYTHON: "C:\\Python38\\python"
      PYTHON_VERSION: "3.8.0"
      PYTHON_ARCH: "32"
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      appveyor_build_worker_image: Visual Studio 2017

    - PYTHON: "C:\\Python36-x64\\python"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "64"
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      appveyor_build_worker_image: Visual Studio 2017

    - PYTHON: "C:\\Python37-x64\\python"
      PYTHON_VERSION: "3.7.4"
      PYTHON_ARCH: "64"
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      appveyor_build_worker_image: Visual Studio 2017

    - PYTHON: "C:\\Python39-x64\\python"
      PYTHON_VERSION: "3.9.0"
      PYTHON_ARCH: "64"
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      appveyor_build_worker_image: Visual Studio 2019

matrix:
  exclude:
    - image: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 16 2019"
    - image: Visual Studio 2019
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %CMAKE_GENERATOR%"

install:
  - "%PYPY_DOWNLOAD%"
  - "set HOME=%APPVEYOR_BUILD_FOLDER%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\\%PYPY_VERSION%"
  - "%PYTHON% -m ensurepip"
  - "%PYTHON% -m pip install -U pip setuptools twine scikit-build wheel cmake"
  - "%PYTHON% setup.py bdist_wheel"
  - ps: "ls dist"

  # Install the wheel to test it
  - "%PYTHON% -m pip install --ignore-installed --pre --no-index --find-links dist/ pygeodiff"

# Appveyor's build step is specific to .NET projects, so we build in the
# install step instead.
build: off

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

test_script:
  - "%PYTHON% -c \"import pygeodiff;\""

on_success:
  - cmd: "if [%APPVEYOR_REPO_TAG%]==[true] %PYTHON% -m twine upload dist\\*.whl --skip-existing"
